FROM ubuntu:latest

LABEL AUTHOR=Krystian
LABEL VERSION=10.10.10
LABEL DESCRIPTION=Plik_Dockera
RUN apt update && apt install nginx -y \
    && apt install curl -y \
    && apt install git -y \
    && apt install wget -y \
    && apt install nano -y

COPY opt/custom_site/index.html /usr/share/nginx/html
ENV BGCOLOR=green
RUN sed -i 's/CHANGE_ME/$BGCOLOR/' /usr/share/nginx/html/index.html

CMD ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log;\
    sed -i 's/CHANGE_ME/$BGCOLOR/' /usr/share/nginx/html/index.html;\
    nginx -g 'daemon off;'
